#%RAML 1.0
title: Test0
baseUri: http:/hello.com/q
/hello:
   /q:
   post:
        body:
             application/json:
                properties:
                   x: number
                   y?: number
        responses:
           200:
